---
title: "Junk"
author: "Tanu Kajla"
date: "4/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(owmr)

#source("Functions.R")'

#---------------------------- Libraries ----------------------------- 

  # Creating a vector of packages used within
  required.packages <- c("base","jsonlite","leaflet","lubridate","magrittr","padr","plotly","purrr","raster",
                         "rgdal","rgeos","rvest","selectr","shiny","shinyjs","sp","stringr","urltools","utils","xml2","xts","zoo","tidyverse","shinydashboard","shinythemes","shinyWidgets",'car','caret','data.table','pROC','ranger','Rtsne','xgboost','caretEnsemble')
  
  # Function to Install and Load R Packages
  install.load.packages <- function(required.packages){
    required.packages <-
      required.packages[!(required.packages %in% installed.packages()[, "Package"])]
    if (length(required.packages)){
      install.packages(required.packages, repos = 'http://cran.us.r-project.org')
    }
    for (package.name in required.packages)
    {
      library(package.name,
              character.only = TRUE,
              quietly = TRUE)
    }
  }
  
  # Call the Function
  install.load.packages(required.packages)
  
  # Including the packages for use
  for (package in required.packages) {
    library(package, character.only = TRUE)
  }

  
library("rebird")
library("mapr")
  
  air <- data.frame(
  airfields = c("KDEN",
                "KDFW",
                "KORD",
                "KSMF"),
  latitude = c(39.86169815,
               32.896801,
               41.9786,
               38.69540024),
  longitude = c(-104.6729965,
                -97.038002,
                -87.9048,
                -121.5910034),
  strikes = c(2814,
              2170,1557,1891))

  
```

```{r}


```

```{r}

Sys.setenv(OWM_API_KEY = "99f521810d0fef37f59930f36dbb2256")
result <- owmr::get_forecast(lat = air[1,2], lon = air[1,3], units = "imperial")
str(result$list)

lubridate::ymd_h()
names(result$list)
forecast<-data.frame("DATE" =  lubridate::ymd_hms(result$list$dt_txt),
                 "M.TEMP" = result$list$main.temp,
                 "M.FL.TEMP" = result$list$main.feels_like,
                 "M.TEMP.MIN" = result$list$main.temp_min,
                 "M.TEMP.MAX" = result$list$main.temp_max,
                 "M.PRES" = result$list$main.pressure,
                 "M.SLP" = result$list$main.sea_level,
                 "M.HUM" = result$list$main.humidity,
                 "M.CL" = result$list$clouds.all,
                 "M.WS" = result$list$wind.speed,
                 "M.WD" = result$list$wind.deg,
                 "3H.RAIN" = result$list$rain.3h)
View(temp)




```


```{r}


for(i in 1:len){
  print(states[i])
  temp<- owmr::get_forecast(city=states[i], unit = "imperial")
  temp<-temp$list$main
  temp$state=states[i]
  #temp$index=1:nrow(temp)
  data<-as.data.frame(rbind(data,temp))
}

head(data)

d=gsub("Odisha","Orissa",data$state)
d=gsub("National Capital Territory of Delhi","Delhi",d)
d=gsub("Uttarakhand","Uttaranchal",d)
data$state=d
data$state=as.character(data$state)

head(data)

```

```{r}
# data %>%  
#   group_by(`AIRPORT ID`) %>% 
#   summarise(Strikes = sum(STRIKECOUNT))

```

```{r}
air <- data.frame(
  airfields = c("KDEN",
                "KDFW",
                "KORD",
                "KSMF"),`
  latitude = c(39.86169815,
               32.896801,
               41.9786,
               38.69540024),
  longitude = c(-104.6729965,
                -97.038002,
                -87.9048,
                -121.5910034),
  strikes = c(2814,
              2170,1557,1891))

head(air)


coord <- air %>% 
  filter(airfields == "KDEN")
lat<- coord[1,2]
long<-coord[1,3]

```



```{r}

#install.packages("auk")
#devtools::install_github("ropensci/rebird")

```


```{r}

getDataAndRunPredict <- function(airfield, strikedate) {
    
    # Get Averages file name from the custom dataframe
    fileNames <-
      air %>% select(avgfilename, modelfilename) %>% filter(airfields == airfield)

    
    # Read the Averages from file system
    data <- readRDS(paste0(fileNames$avgfilename))

    # Convert the input to date format and convert to Day of Week
    #data <-
      data %>% filter(DAYOFYEAR == lubridate::yday(as.Date(strikedate)))

    # Create Season columns as required by the input to the model
    data <-
      data %>% add_column(
        SEASON.winter = 0,
        SEASON.summer = 0,
        SEASON.fall = 0,
        SEASON.spring = 0
      )

    # Fill the season columns based on the value in the Averages dataframe
    if (data$SEASON == 1) {
      data$SEASON.winter <- 1
    } else if (data$SEASON == 2) {
      data$SEASON.spring <- 1
    } else if (data$SEASON == 3) {
      data$SEASON.summer <- 1
    } else {
      data$SEASON.fall <- 1
    }

    # Remove Season column and make all columns numeric
    data <-
      data %>% select(-SEASON) %>% mutate_all(as.numeric)

    
    # Load model from RDS
    model <- readRDS((paste0(fileNames$modelfilename)))
    
    # Call predict with type = raw to get the risk levels
    predicted.raw <- predict(model, data, type = "raw")
    
    # Call Predict with type = prob to get probabilities
    predicted.prob <- predict(model, data, type = "prob")
    
    predicted.prob
    # Create results dataframe for use in UI
    strike.results <-
      data.frame("STRIKERISKLEVEL" = predicted.raw,
                 "STRIKEPROBABILITY" = predicted.prob)
    
    # Return dataframe
    strike.results
  }
# #Run the function
# risk<-getDataAndRunPredict("KDEN",Sys.Date())
# #Add the date 
# risk$date <- seq(ymd("2020/1/1"), ymd("2020/12/31"), by = "day")
# #Add the month 
# risk$month <- lubridate::month(risk$date,label= TRUE, abbr = FALSE)
# #counts the number of lines assigned by the month and risk level 
# risk %>%  group_by(month,STRIKERISKLEVEL) %>% 
#   tally()
# 
# tail(risk)

```

```{r}

# birds2 <- spocc::occ(from = "ebird",
#                        ebirdopts = list(method = "ebirdgeo",
#                                         species = NULL,
#                                         lat = air[1,3],
#                                         lng = air[1,2],
#                                         back = 30,
#                                         dist = as.numeric(
#                                           units::set_units(dist, "mi"))))
# 
# mapr::map_leaflet(birds2,
#                   color = "blues9",
#                   lat = birds2$ebird$meta$opts$lat,
#                   lng = birds2$ebird$meta$opts$lat)



# Group by zipcode and sum of offense counts
# heatmap.by.zipcode <-
#   crime_data %>% dplyr::select(zip, latitude, longitude,offense_count) %>%
#   group_by(
#     zip,
#     latitude, 
#     longitude
#   ) %>%  dplyr::summarize(Count = sum(offense_count)) %>%
#   arrange(desc(Count))
# add a dark matter map and display the intensity



#install.packages("units")
library(rebird)


EBIRD_KEY <- 'ldto4uofjnf7'
dist <- 20

#region_codes = ['US-CO-031','US-CO-001','US-CO-005', 'US-CO-059']

birds <- rebird::ebirdgeo(species = NULL,
                          lat = air[1,2],
                          lng = air[1,3],
                          back = 30,
                          dist = as.numeric(
                            units::set_units(dist, "mi")),
                          key = EBIRD_KEY)

birds<-birds %>% group_by(lat,lng) %>% 
  summarise(howMany = sum(howMany))


leaflet(birds) %>% addProviderTiles(providers$OpenStreetMap) %>%
  setView(zoom = 11, lat = air[1,2], lng = air[1,3]) %>%
  addCircleMarkers(air[1,2],air[1,3]) %>% 
  owmr::add_weather(result,lat = air[1,2], lng = air[1,3]) %>% 
  leaflet.extras::addHeatmap(
    lat = ~ birds$lat,
    lng = ~ birds$lng,
    blur = 20,
    max = 0.05,
    radius = 15)


Sys.setenv(OWM_API_KEY = "99f521810d0fef37f59930f36dbb2256")
result <- owmr::get_forecast(lat = air[1,2], lon = air[1,3], units = "imperial") %>%
  owmr_as_tibble()


owm_data <- find_city(lat =air[1,2] , lon = air[1,3] , units = "imperial") %>%
  owmr_as_tibble()
map <- leaflet() %>% addTiles() %>%
  add_weather(
    owm_data,
    template = "<b>{{name}}</b>, {{temp}}<c2><b0>F",
    icon = owm_data$weather_icon)
map


```



```{r}

leaflet(birds) %>% addProviderTiles(providers$OpenStreetMap) %>% 
  setView(zoom = 11, lat = air[1,2], lng = air[1,3]) %>%
  addProviderTiles(providers$OpenWeatherMap.Precipitation,
                   options=providerTileOptions(apiKey="99f521810d0fef37f59930f36dbb2256")) %>% 
  leaflet.extras::addHeatmap(
    lat = ~ birds$lat,
    lng = ~ birds$lng,
    blur = 20,
    max = 0.05,
    radius = 15) 


```


```{r}
# bounds <- map('state', c('Texas'), fill=TRUE, plot=FALSE)
# icons <- awesomeIcons(
#     icon = 'disc',
#     iconColor = 'black',
#     library = 'ion', # Options are 'glyphicon', 'fa', 'ion'.
#     markerColor = 'blue',
#     squareMarker = TRUE
# )
# crime_data_map <- crime_data %>% dplyr::select(zip, latitude, longitude) %>% distinct
# maxLong = max(crime_data_map$longitude)
# maxLat = max(crime_data_map$latitude)
# minLong = min(crime_data_map$longitude)
# minLat = min(crime_data_map$latitude)
# # Create the Leaflet map widget and add some map layers.
# # We use the pipe operator %>% to streamline the adding of
# # layers to the leaflet object. The pipe operator comes from
# # the magrittr package via the dplyr package.
# leaflet(data = crime_data_map) %>%
#   setView(zoom = 100, lat = 29.10, lng = -95.10) %>%
#   addProviderTiles("CartoDB.Positron", group = "Map") %>%
#   addProviderTiles("Esri.WorldImagery", group = "Satellite") %>%
#   addProviderTiles("Esri.WorldShadedRelief", group = "Relief") %>%
#   # Marker data are from the sites data frame. We need the ~ symbols
#   # to indicate the columns of the data frame.
#   addMarkers(
#     ~ longitude,
#     ~ latitude,
#     label = ~ zip,
#     group = "Sites",
#     icon = icons
#   ) %>%
#   addPolygons(
#     data = bounds,
#     group = "States",
#     weight = 2,
#     fillOpacity = 0
#   ) %>%
#   addScaleBar(position = "bottomleft") %>%
#   addLayersControl(
#     baseGroups = c("Map", "Satellite", "Relief"),
#     overlayGroups = c("Sites", "States"),
#     options = layersControlOptions(collapsed = FALSE)
#   ) %>% fitBounds(minLong, minLat, maxLong, maxLat)

document.querySelector(".small-box").parentNode.setAttribute("onclick", "window.open('https://economictimes.indiatimes.com', 'newwindow', 'width=300,height=250'); return false;")


```


```{r}
leaflet() %>%
    addProviderTiles(providers$OpenStreetMap) %>%
    setView(-122.36075812146, 35.6759920119894, zoom = 11) %>% 
    addProviderTiles(providers$OpenWeatherMap.Precipitation,
        options=providerTileOptions(apiKey="99f521810d0fef37f59930f36dbb2256"))
```


```{r}

#Map of original items in the ap
    # mymap <- leaflet() %>%
    #   addProviderTiles(providers$OpenStreetMap,
    #                    options = providerTileOptions(noWrap = TRUE)) %>%
    #   addMarkers(lng = air$longitude, lat = air$latitude, popup = names(air)) %>%
    #   addCircleMarkers(air$longitude,air$latitude,
    #                    sqrt(air$strikes) * 0.79899999) %>%
    #   addPopups(air$longitude,air$latitude,
    #             htmltools::htmlEscape(paste(
    #               paste(air$airfields, sep = " "),
    #               paste("Strikes:", as.character(air$strikes), sep = " "),
    #               sep = ", ")))


```


```{r}

# valueBox(tags$p(HTML("Biometric"), 
#                 style = "font-size: 100%", 
#                 style = "font-weight: bold"), 
#          subtitle = div(img(src = "FAA.png", 
#          height = "38", 
#          width = "80"), 
#          style = "text-align: right;"), 
#          color = "blue", width = 3)
# 
# 
#   valueBox(tags$p(HTML("Biometric"),
#            style = "font-size: 100%",
#            style = "font-weight: bold"),
#     subtitle = div(img(src = "images/FAA.png",
#                        height = "38",
#                        width = "80"),
#                    style = "text-align: right;"),
#     color = "blue", width = 3)
#   })

#OG MAp
    # mymap <- leaflet() %>%
    #   addProviderTiles(providers$OpenStreetMap,
    #                    options = providerTileOptions(noWrap = TRUE)) %>%
    #   addMarkers(lng = air$longitude, lat = air$latitude, popup = names(air)) %>%
    #   addCircleMarkers(air$longitude,air$latitude,
    #                    sqrt(air$strikes) * 0.79899999) %>%
    #   addPopups(air$longitude,air$latitude,
    #             htmltools::htmlEscape(paste(
    #               paste(air$airfields, sep = " "),
    #               paste("Strikes:", as.character(air$strikes), sep = " "),
    #               sep = ", ")))

```